  version: '3.8'

  services:
    app:
      build: .
      ports:
        - "8080:8080"
      environment:
        - DATABASE_URL=postgres://user:password@db:5432/mydbname?sslmode=disable
      depends_on:
        db:
          condition: service_healthy

    db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: mydbname
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "user"]
        interval: 30s
        timeout: 10s
        retries: 5