// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// publicationCreater is an autogenerated mock type for the publicationCreater type
type publicationCreater struct {
	mock.Mock
}



// CreatePublication provides a mock function with given fields: ctx, ID, MaterialType, Status, Title, Content, CreatedAt, UpdatedAt
func (_m *publicationCreater) CreatePublication(ctx context.Context, ID uuid.UUID, MaterialType string, Status string, Title string, Content string, CreatedAt time.Time, UpdatedAt time.Time) error {
	ret := _m.Called(ctx, ID, MaterialType, Status, Title, Content, CreatedAt, UpdatedAt)

	if len(ret) == 0 {
		panic("no return value specified for CreatePublication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, string, time.Time, time.Time) error); ok {
		r0 = rf(ctx, ID, MaterialType, Status, Title, Content, CreatedAt, UpdatedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMaterialCreater creates a new instance of publicationCreater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublicationCreater(t interface {
	mock.TestingT
	Cleanup(func())
}) *publicationCreater {
	mock := &publicationCreater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
