// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	model "github.com/KillReall666/schooldocumentmanagment/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// publicationUpdater is an autogenerated mock type for the publicationUpdater type
type publicationUpdater struct {
	mock.Mock
}

// UpdatePublicationByUUID provides a mock function with given fields: ctx, publications
func (_m *publicationUpdater) UpdatePublicationByUUID(ctx context.Context, publications model.Publication) error {
	ret := _m.Called(ctx, publications)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePublicationByUUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Publication) error); ok {
		r0 = rf(ctx, publications)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newPublicationUpdater creates a new instance of publicationUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newPublicationUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *publicationUpdater {
	mock := &publicationUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
